// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcA1giSRucbijjP-crn9bXwxAYUaLDa50',
    appId: '1:17624100117:web:d84b927ff41bbbf6418d1c',
    messagingSenderId: '17624100117',
    projectId: 'petstore-119d6',
    authDomain: 'petstore-119d6.firebaseapp.com',
    storageBucket: 'petstore-119d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbHPSHk3bi47QenazeyOLngJg6IIo4SqA',
    appId: '1:17624100117:android:3065ebb384baa933418d1c',
    messagingSenderId: '17624100117',
    projectId: 'petstore-119d6',
    storageBucket: 'petstore-119d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDivNnqp5C5GKOQqb1XJS1brMwXOYjjd9w',
    appId: '1:17624100117:ios:fdb7a5ef6365ce7d418d1c',
    messagingSenderId: '17624100117',
    projectId: 'petstore-119d6',
    storageBucket: 'petstore-119d6.firebasestorage.app',
    iosClientId: '17624100117-9kv5hrh2661i9nuus7ticvbea4qgbqh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.petStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDivNnqp5C5GKOQqb1XJS1brMwXOYjjd9w',
    appId: '1:17624100117:ios:fdb7a5ef6365ce7d418d1c',
    messagingSenderId: '17624100117',
    projectId: 'petstore-119d6',
    storageBucket: 'petstore-119d6.firebasestorage.app',
    iosClientId: '17624100117-9kv5hrh2661i9nuus7ticvbea4qgbqh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.petStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcA1giSRucbijjP-crn9bXwxAYUaLDa50',
    appId: '1:17624100117:web:2c993686ba4c8020418d1c',
    messagingSenderId: '17624100117',
    projectId: 'petstore-119d6',
    authDomain: 'petstore-119d6.firebaseapp.com',
    storageBucket: 'petstore-119d6.firebasestorage.app',
  );
}
